from mocha import ui

mocha_widgets = ui.get_widgets()
main_window = mocha_widgets["MainWindow"]

main_window.setStyleSheet(
    "QMainWindow { background-color: #21252B;}"
    "QMainWindow::separator {background-color: #282C34;}"
    "QDockWidget QWidget {background-color: #21252B;}"
    "QPushButton { background-color: #21252B; color: #979EAA; font: bold}"
    "QPushButton::hover { background-color: #4f545E; color: #979EAA; font: bold}"
    "QToolButton { background-color: #21252B; }"
    "QToolButton:checked { background-color: #6494ED; }"
    "QToolButton:hover { background-color: #4f545E; }"
    "QLabel {font: 14px;}"
    "QFrame {background-color: #21252B;}"
    "QToolBox {background-color: #282C34;}"
    "QListView {background-color: #282C34;}"
    "QTreeView {background-color: #282C34;}"
    "QLineEdit {background-color: #21252B;}"
    "QComboBox {background-color: #282C34;}"
    "QGroupBox {background-color: #282C34;}"
    "QCheckBox {background-color: #282C34;}"
    "QRadioButton {background-color: #282C34;}"
    "QToolBar {background-color: #282C34;}"
    "QTableView {background-color: #282C34;}"
    "QMenu {background-color: #282C34;}"
    "QMenuBar {background-color: #282C34;}"
    "QProgressBar {background-color: #282C34;}"
    "QSlider {background-color: #282C34;}"
    "QScrollBar {background-color: #282C34;}"
    "QDialog {background-color: #282C34;}"
    "QTextFrame {background-color: 21252B;}"
    "QStatusBar {background-color: #282C34;}"
    "#timelineControlsW {background-color: #282C34;}"
    "#sldrFrameNumber::enabled {selection-background-color: red;}"
    "QTabBar::tab {background: #2E2B30;}"
    "QTabBar::tab:selected {background: black;}"
    "QTabWidget::pane QWidget{background-color: #282C34;}"
)
